version: '3'

services:
  app:
    build: .
    ports:
      - 3030:3030
    volumes:
      -  .:/home/node/app
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_DATABASE=venda
      - JWT_SECRET=sua-chave-secreta
      - JWT_EXPIRES_IN=7d
    
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=venda
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5439:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 16543:80
    depends_on:
      - db

volumes:
  dbdata:
